library(igraph)
g1 <- graph( edges=c(1,2,2,3,3,1), n=3, directed=F)
plot(g1)
g2 <- graph( edges=c(1,2,2,3,3,1), n=10, directed=F)
plot(g2)
g3 <- graph( c("John", "Jim", "Jim", "Jill", "Jill", "John"))
plot(g3)
g4 <- graph( c("John", "Jim", "Jim", "Jack", "Jim", "Jack", "John", "John"), isolates=c("Jesse","Janis","Jennifer","Justin"))
plot(g4)
plot(g4, edge.arrow.size=0.5)
plot(g4, edge.arrow.size=0.5, vertex.color="gold")
plot(g4, edge.arrow.size=0.5, vertex.color="gold", vertex.size=15)
plot(g4, edge.arrow.size=0.5, vertex.color="gold", vertex.size=15, vertex.frame.color="gray")
plot(g4, edge.arrow.size=0.5, vertex.color="gold", vertex.size=15, vertex.frame.color="gray", vertex.label.dist=2)
plot(g4, edge.arrow.size=0.5, vertex.color="gold", vertex.size=15, vertex.frame.color="gray", vertex.label.dist=2, vertex.label.color="black")
plot(g4, edge.arrow.size=0.5, vertex.color="gold", vertex.size=15, vertex.frame.color="gray", vertex.label.dist=2, vertex.label.color="black",edge.curved=0.2)
plot(g4, edge.arrow.size=0.5, vertex.color="gold", vertex.size=15, vertex.frame.color="gray", vertex.label.dist=2, vertex.label.color="black",edge.curved=0.2,vertex.label.cex=0.8)
links <- read.csv("~/Research/PER/REU/2017/R/MAMCR/netscix2016/Dataset1-Media-Example-EDGES.csv", header=T, as.is=T)
nodes <- read_csv("~/Research/PER/REU/2017/R/MAMCR/netscix2016/Dataset1-Media-Example-EDGES.csv")
head(nodes)
head(links)
nrow(nodes); length(unique(nodes$id))
nrow(links); nrow(unique(links[,c("from","to")]))
links <- aggregate(links[,3], links[,-3],sum)
links <- links[order(links$from, links$to),]
colnames(links)[4] <- "weight"
rownames(links) <- NULL
nodes2 <- read.csv("~/Research/PER/REU/2017/R/MAMCR/netscix2016/Dataset2-Media-User-Example-NODES.csv", header=T, as.is=T)
links2 <- read.csv("~/Research/PER/REU/2017/R/MAMCR/netscix2016/Dataset2-Media-User-Example-EDGES.csv", header=T, row.names=1)
net2 <- graph_from_incidence_matrix(links2)
table(V(net2)$type)
net2.bp <- bipartite.projection(net2)
plot(net2.bp$proj1, vertex.label.color="black", vertex.label.dist=1, vertex.size=7, vertex.label=nodes2$media[!is.na(nodes2$media.type)])
plot(net2.bp$proj2, vertex.label.color="black", vertex.label.dist=1, vertex.size=7, vertex.label=nodes2$media[is.na(nodes2$media.type)])

